### ISSUE TITLE
Feature: `pizza insights repo` for individual repo insights

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#10]
### Type of feature

🍕 Feature

### Current behavior

Once we introduce a `insights` subcommand, it may also be interesting to get individual repository insights.

### Suggested solution

A `repo` subcommand on the `insights` command that takes a github url and queries our API for information we've indexed would be interesting.

```
$ pizza insights repo <github-url>

ACTIVITY     PR OVERVIEW    PR VELOCITY    SPAM      CONTRIBUTORS
High         6 open PRs     30%            0         jpmcb, BekahHW, bdougie

See the full dashboard: https://insights.opensauced.pizza/{page-to-insights}
```

or with a `--output` flag:

```
$ pizza insights repo <github-url> --output json
{
  "activity": "high",
  "open-prs": 6,
  "pr-velocity": 0.3
  "spam": 0,
  "contributors": ["jpmcb", "BekahHW", "bdougie"]
}
```

This is mostly an idea but would be interesting to explore.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by cecobask** [comment]
@jpmcb, I will be happy to take on this issue!
It's quite similar to the work I did on #5.

**Comment by cecobask** [comment]
Hi @jpmcb, I'm about to start working on this feature.
Should the command only take one repository at a time or I can extend it to accept multiple?

**Comment by bdougie** [comment]
Agreed. The scope of the last PR increase a bit and would be better to do a follow up to make this work with a single repo for now and a follow up issue/pr for multiple repos.
