### ISSUE TITLE
Bug: `pizza generate codeowners` - files with `[` or `]` cause errors for github `CODEOWNERS`

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#100]
### Describe the bug

For files that contain literal `[` or `]` characters, the `CODEOWNERS` file will be malformed:

```
Invalid pattern on line 238: both `[` and `]` must be escaped with a `\`

pages/s/[org]/[repo]/index.tsx @zeucapua @brandonroberts @zeucapua
```

### Steps to reproduce

Run the codeowners command on a repo with files that container `[` and `]` like our open-sauced/app repo

**Comment by nickytonline** [comment]
Note that newer file based routing also uses `+`, `(`, and `)` characters as well.

**Comment by jpmcb** [comment]
Good to know: the `CODEOWNERS` syntax follows the `.gitignore` syntax: https://git-scm.com/docs/gitignore#_pattern_format and seems that we just need to put a `\` in front of those characters to escape them in the path
