### ISSUE TITLE
Feature: Automatically detect in root of repository path for .sauced.yaml

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/pizza-cli#102]
## Description

As a user of the pizza CLI,I want the CLI to autodetect my .sauced.yaml in the root of the path I specify, so that I do not have to explicitly pass a flag for it.

e.g. `pizza generate codeowners ./` instead of `pizza generate codeowners ./ -c ./.sauced.yaml`

## Acceptance Criteria
- generates a CODEOWNERS or OWNERS file if the path specified for a repo contains a .sauced.yaml
- errors generating a CODEOWNERS or OWNERS file if the path specified for a repo does not contain a .sauced.yaml
- Should be already covered, but error if the explicitly set file path for a .sauced.yaml is not found

**Comment by jpmcb** [comment]
+1

> errors generating a CODEOWNERS or OWNERS file if the path specified for a repo does not contain a .sauced.yaml

I'd say the fallback should be to look in the user's home directory under `~/.sauced.yaml` (which is the current behavior) So the true error path is _**neither**_ a local `.sauced.yaml` file was found nor a home `~/.sauced.yaml` was found
