### ISSUE TITLE
Feature: add more linters in `golangci-lint`

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#124]
### Suggested solution

There are a number of automated linters in `golangci-lint` we could start taking advantage of:

https://golangci-lint.run/usage/linters/

Let's enable more of these and refactor where needed

**Comment by nickytonline** [comment]
Any preferences to which ones to activate?

These ones look decent to add:
- [gci](https://golangci-lint.run/usage/linters/#gci)
- [gocognit](https://golangci-lint.run/usage/linters/#gocognit)
- [gocyclo](https://golangci-lint.run/usage/linters/#gocyclo)
