### ISSUE TITLE
Feature: update `README` with latest docs and demo video

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#149]
### Suggested solution

We'll want a few things in the README:
- Updated docs and help for the yaml config
- A demo video showing how to use the CLI

**Comment by bdougie** [comment]
I just did a quick walkthrough generating a codeowners file using what we have deployed today. 

https://opensauced.rewatch.com/video/61p3lcbntixcq1gz-pizza-cli-demo-test-001

1. I created a `.sauced.yaml` offline to copy and paste. I think this PR would be great accelerate that part of the demo. https://github.com/open-sauced/pizza-cli/pull/137
2. I think the "ask" to create an OpenSauced contributor insight is too early and should be asked after the file is created. My thought is a user expects to get the CODEOWNERS as the value. The insight would be a bonus. 

Happy to hear thoughts, or if there is a plan/roadmap somewhere else I can comment on, let me know.
