### ISSUE TITLE
Feature: `pizza generate codeowners` config file should defualt to local path vs. local path

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#155]
### Suggested solution

The default experience is to use the `~/.sauced.yaml` config vs. the one within the directory targeted by the CLI:

```
$ pizza generate codeowners /path/to/repo
```

If there's both a `~/.sauced.yaml` and a `/path/to/repo/.sauced.yaml`, it'll pick the `~/.sauced.yaml` file

---

The default behavior should be flipped

**Comment by brandonroberts** [comment]
Closed by https://github.com/open-sauced/pizza-cli/pull/158
