### ISSUE TITLE
Feature: generate codeowners for a specific user 

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/pizza-cli#189]
### Suggested solution

Since we can generate a CODEOWNERS file to show who has "most recently touched the files," it would be helpful to also generate one for a specific user (from those contributors) to see only the files they've worked on recently.

It would be great to also pass a time range and maybe mark those files to make them differentiable.

**Comment by brandonroberts** [comment]
Yes, you can populate your `.sauced.yaml` with a single user and generate the code owners file. Every file you've touched will be attributed to you, and the other files won't have a contributor unless you define a fallback contributor or group.
