### ISSUE TITLE
Feature: `pizza login` to get user's bearer token

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#20]
### Type of feature

🍕 Feature

### Current behavior

Many of the OpenSauced API endpoints require bearer authentication. We should add a `pizza login` command that gets the user's bearer token, stores it (much like a cookie), and can be used for various operations.

This will enable us to do some pretty interesting things with the Pizza CLI (like get a user's highlights, getting their dashboards, etc.)

### Suggested solution

1. A command can be called to log a user in with `pizza login`
2. This command should open a new browser tab. This should be our authentication endpoint (supabase?) and should have a `?redirect=` back to a locally started Go web server in order to capture the bearer token
3. Once the user is logged in and the redirect is completed, the bearer token should be stored within a `~/.pizza/` directory. This is essentially like storing a bearer token cookie in the browser

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
@Anush008 worked on this in the chrome extension and might be able to provide some context on this. 

https://github.com/open-sauced/ai/blob/beta/src/utils/checkAuthentication.ts

**Comment by Anush008** [comment]
Hey. @jpmcb, @bdougie. Can I take this?
I got a pretty good idea of Supabase's new auth flow when working on https://github.com/open-sauced/ai/pull/230.

**Comment by jpmcb** [comment]
Go for it @Anush008 - happy to help with the Go / Cobra code!!
