### ISSUE TITLE
Feature: Specify Output Directory for CODEOWNERS file

### ISSUE THREAD

**Issue by udaypatel1** [open-sauced/pizza-cli#222]
### Suggested solution

In it's current state, the following are available options for generating a CODEOWNERS file via the CLI:

```
Flags:
  -h, --help                help for codeowners
      --owners-style-file   Generate an agnostic OWNERS style file instead of CODEOWNERS.
  -r, --range int           The number of days to analyze commit history (default 90) (default 90)

Global Flags:
  -c, --config string       The codeowners config
      --disable-telemetry   Disable sending telemetry data to OpenSauced
  -l, --log-level string    The logging level. Options: error, warn, info, debug (default "info")
      --tty-disable         Disable log stylization. Suitable for CI/CD and automation
```

I want to specify an output directory whereby I can put my generated CODEOWNERS file.

Example: `pizza generate codeowners . -o .bitbucket/`

In Bitbucket SCM, the CODEOWNERS file must be under `.bitbucket/` and so this way, I can explicitly define where to put the auto-generated file.

This would natively support an output flag `-o` for this portion of the CLI and give flexibility in defining where to put the CODEOWNERS file in your repository.

Thanks! 😁🚀

**Comment by jpmcb** [comment]
Thanks for the issue! I've assigned you!!
