### ISSUE TITLE
Feature: npm install pizza

### ISSUE THREAD

**Issue by bdougie** [open-sauced/pizza-cli#27]
### Type of feature

🍕 Feature

### Current behavior

Is it possible to distribute this cli on npm or would that get weird? I ask because we own the [pizza](https://www.npmjs.com/package/pizza) npm package and it would be a nice name to syndicate this work from. 

I have not explored the security concerns or issues if any, but happy to add an NPM token to the Actions secrets if we want to explore this.

### Suggested solution

Looks like you do so via the goreleaser. Examples of other doing it. 

- https://blog.xendit.engineer/how-we-repurposed-npm-to-publish-and-distribute-our-go-binaries-for-internal-cli-23981b80911b
- https://blog.bywachira.com/post/create-cli-with-golang-and-publish-on-npm

### Additional context

Just look to see if its possible. 

<img src="https://media3.giphy.com/media/B8rOUw1NAJ70L1AXWA/giphy-downsized-medium.gif"/>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Good question: I'd imagine it's possible, it just might be a matter of getting the build right. I'd have to look into it 👀

**Comment by Anush008** [comment]
Adding to this, the blog posts above use the `go-npm` package to download the binary.
It expects a `package.json` which looks something like this: 
```
{
  "name": "@opn-sauced/pizza-cli",
  "version": "0.0.0",
  "description": "",
  "scripts": {
    "postinstall": "go-npm install",
    "preuninstall": "go-npm uninstall"
  },
  "dependencies": {
     "go-npm": "^0.1.9"
  },
  "goBinary": {
    ###  Name of the binary file and what npm will alias as
    "name": "pizza-cli",
    ### Where to add the binary, could be anywhere. NPM will add it to $PATH automatically
    "path": "./bin",
    ### Dynamic URL pointing to the binary location based on version, platform, and the arch
    "url": "https://github.com/open-sauced/pizza-cli/releases/download/v{{version}}/pizza_{{version}}_{{platform}}_{{arch}}.tar.gz"
  }
}
```

The version number is fetched from the `version` of the `package.json` file.
So it needs to be in sync with version of the release. That calls for a GH Action, that'll bump the version and do `npm publish`

**Comment by Anush008** [comment]
🎉🎉🎉
