### ISSUE TITLE
Feature: OpenSauced API Golang client

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#28]
### Type of feature

🍕 Feature

### Current behavior

This probably needs to be in its own git repo / go module so it can be independently imported, but we should have some canotical way of generating and importing a Go client for the OpenSauced API.

This way, we will never have to worry about drift in our various Go projects.

### Suggested solution

We do generate a swagger doc and I believe there are ways to generate clients in different languages based on the swagger doc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Agreed. I am all for a separate repo (go-opensauced?) for a client. I think the open API spec will provide a path for it.

**Comment by Anush008** [comment]
Just tried it out.
The output was impressive and offers several customization features.
https://openapi-generator.tech/docs/customization
Multiple installation options too.

**Comment by Anush008** [comment]
Just tried it out.
The output was great. I found that there a quite some customisation options.
https://openapi-generator.tech/docs/templating

**Comment by jpmcb** [comment]
Closed with the creation of https://github.com/open-sauced/go-api ✨
