### ISSUE TITLE
Feature: provide contributor insights

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#5]
### Type of feature

🍕 Feature

### Current behavior

Currently, via the CLI, there's no way to see insights for a provided repos.

### Suggested solution

We should add an `insights` command that has a `contributors` subcommand to start.

When invoked with a git repo, it provides some very basic insights based on the commits to the user:

```
$ pizza insights contributors <git-repo>
Over last 30 days

New: 6
Recurring: 2
```

Should also provide the ability to specify the time range:
```
$ pizza insights contributors <git-repo> --time 60d

Over last 60 days:

New contributors: 6
Recurring contributors: 2
```

If the repo is a GitHub repo (which we have indexed data for from the API backend), we should generate a link to the insights page:

```
$ pizza insights contributors https://github.com/open-sauced/pizza-cli --time 60d

Over last 60 days:

New contributors: 6
Recurring contributors: 2

See more at: https://insights.opensauced.pizza/{insight-page}
```

The above will include a few calls to the API so there are some changes that probably need to be made there as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by cecobask** [comment]
Hi @jpmcb, I just discovered this project and I’m interested in working on it. Can I have this issue assigned to me?

**Comment by jpmcb** [comment]
Hi @cecobask! Thanks for reaching out and showing interest. This will require integrating with a few of the newer API endpoints we have, for example, for new contributors, you'll want to use: https://github.com/open-sauced/api/pull/223

If that sounds like something you're up for tackling, I'll assign you and I'm happy to help with anything you come up against!

**Comment by cecobask** [comment]
Sounds good to me, @jpmcb!

First, I want to get an understanding of the APIs. I followed the instructions and did the following:
- Forked and cloned [open-sauced/api](https://github.com/open-sauced/api)
- Setup a project on Supabase and created `.env` file in the root of the repository with the required secrets
- Provisioned a Postgres container using the provided Dockerfile
- Installed the needed dependencies and successfully ran the application locally
- Tested a couple of endpoints locally but soon realized the tables in the database need to be created first 

I have a couple of questions:
- Is there an automated approach to execute the database migrations locally?
- Which endpoint can I use to initiate the authentication flow and retrieve a bearer token?

I think the 2 points above are important for any new contributor and should be added to the README.

Thanks in advance!

**Comment by jpmcb** [comment]
> Is there an automated approach to execute the database migrations locally?

You can apply the migrations using `psql`. And you can apply them all automatically via some bash:

https://github.com/open-sauced/api/issues/226

> Which endpoint can I use to initiate the authentication flow and retrieve a bearer token?

That is probably blocked on #20. So for now, look at just using non-authed contributor insights

**Comment by cecobask** [comment]
@jpmcb, I've submitted a pull request.
Please, review when you get a chance 👍🏻
