### ISSUE TITLE
Bug: `--period` flag is broken

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#66]
### Describe the bug

The period flag seems to have broken at some point:

```
❯ pizza insights contributors https://github.com/open-sauced/app -p 45
Error: error while calling 'ContributorsServiceAPI.FindAllChurnPullRequestContributors' with repository 501028599': 400 Bad Request
error while calling 'ContributorsServiceAPI.NewPullRequestContributors' with repository 501028599': 400 Bad Request
error while calling 'ContributorsServiceAPI.FindAllRecentPullRequestContributors' with repository 501028599': 400 Bad Request
error while calling 'ContributorsServiceAPI.FindAllRepeatPullRequestContributors' with repository 501028599: 400 Bad Request

Usage:
  pizza insights contributors url... [flags]

Flags:
  -f, --file string    Path to yaml file containing an array of git repository urls
  -h, --help           help for contributors
  -p, --period int32   Number of days, used for query filtering (default 30)

Global Flags:
      --beta                Shorthand for using the beta OpenSauced API endpoint ("https://beta.api.opensauced.pizza"). Supersedes the
                            '--endpoint' flag
      --disable-telemetry   Disable sending telemetry data to OpenSauced
  -e, --endpoint string     The API endpoint to send requests to (default "https://api.opensauced.pizza")
  -o, --output string       The formatting for command output. One of: (table, yaml, csv, json) (default "table")
```

### Steps to reproduce

1. call the `insights` command with a repo and the `-p / --period` flag defined
2. Notice the 400, bad request responses

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by k1nho** [comment]
I think this might be because the API only accepts 7,30,90 as valid ```range``` values, so any other value just fails.

**Comment by jpmcb** [comment]
Ahh, you're totally right. Great catch @k1nho - it's pretty confusing from the `pizza` CLI perspective to not have some of that information surfaced. Maybe we consider adding a client side restriction so you can only enter valid API values.

**Comment by udaypatel1** [comment]
Just a note – this Issue seems like it should be closed as well, the related PR and change has been merged. (#67)
