### ISSUE TITLE
Feature: `pizza show <git-repo-url>` for a realtime dashboard of repo activity

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#9]
### Type of feature

🍕 Feature

### Current behavior

Via the CLI, there's not a good way to show a realtime view of events happening on a repository.

### Suggested solution

We should implement a `show` command that takes a git repo URL and displays the realtime events (commits) for that repo:

```
$ pizza show <git-repo-url>
```

This could use some Terminal-User-Interface (TUI) to makeup a nice looking display.

The use-case here is maybe an office with a centralized monitor where people want to display a terminal with these realtime metrics of a repo they are watching.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Perhaps there are some existing libraries or examples we can borrow from for the visualizations. I shared the [nba-go](https://github.com/homerchen19/nba-go) as my favorite example, but also citing for others. 

Also the charmcli project might have some interesting visualizations in their org or in the the works. Happy to reach out if a collaboration is of interest.

**Comment by k1nho** [comment]
> Also the charmcli project might have some interesting visualizations in their org or in the the works. Happy to reach out if a collaboration is of interest.

Yep, lots of the Charm libs use Go. [BubbleTea](https://github.com/charmbracelet/bubbletea), [Bubbles](https://github.com/charmbracelet/bubbles), and [Lipgloss](https://github.com/charmbracelet/lipgloss) are the ones I've seen used the most in combination to create TUI's

**Comment by k1nho** [comment]
@jpmcb Do we know the fields to be displayed for this?  and are we are requesting to pizza-oven for some commit data periodically after some seconds to be realtime ? I think we may be able to leverage Charm Bubbles table component structure for this. I can explore this one.

**Comment by bdougie** [comment]
If we have commits data already we can visualize commits over a time period in a line graph, similar to how we do in the UI.

**Comment by k1nho** [comment]
>New contributors for a repo: https://api.opensauced.pizza/#/Contributors%20service/newPullRequestContributors
Churn contributors for a repo: https://api.opensauced.pizza/#/Contributors%20service/findAllChurnPullRequestContributors

It seems these two endpoints are broken atm, just returning 500 status. ```v1/contributors/insights/recent``` and ```v1/contributors/search``` seem to be the only two working.

**Comment by jpmcb** [comment]
@k1nho - how are you using the API endpoint?

For new contributors, this works fine for me:
```sh
curl -X 'GET' \
  'https://api.opensauced.pizza/v1/contributors/insights/new?page=1&limit=10&range=30&topic=javascript&repo=open-sauced%2Finsights&repoIds=501028599' \
  -H 'accept: application/json'
```

And for churn, this also works:
```sh
curl -X 'GET' \
  'https://api.opensauced.pizza/v1/contributors/insights/churn?page=1&limit=10&range=30&repoIds=501028599' \
  -H 'accept: application/json'
```

`501028599` is the repo id in the DB for the open-sauced/insights repo.

The `new` endpoint is abit wonky since it expects those query params that don't make alot of sense: i.e., `topic` and `name` doesn't make alot of sense.

**Comment by jpmcb** [comment]
Closed by https://github.com/open-sauced/pizza-cli/pull/24
