### ISSUE TITLE
Feature: give `pizza login` page a refresh

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#91]
### Suggested solution

This is the current page that gets displayed after a successful login:

![Screenshot 2024-08-26 at 1 35 01 PM](https://github.com/user-attachments/assets/428656c4-5279-47a5-94c5-ea679e7e31a6)

This was built very early on without much thought for design: we should give this page a refresh. It's just basic HTML and CSS with a small `script` for the countdown: https://github.com/open-sauced/pizza-cli/blob/beta/cmd/auth/success.html

In my opinion, the simpler the better: it probably doesn't even need a countdown timer.

cc @isabensusan if you have any design ideas

**Comment by nickytonline** [comment]
I'll put up a small PR that we can iterate on. Will probably go with the dark backround/new logo.
