### ISSUE TITLE
Feature: Auto generate a `.sauced.yaml` file

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#97]
The current experience of `pizza generate codeowners` requires either:

- an existing `~/.sauced.yaml` file in the users home directory
- using the `-c` flag with the path to a yaml config file

Probably the biggest pain point for using `pizza generate codeowners` is that people likely won't have created any attributions in a file yet.

We should think about a easy path, default experience for people who don't yet have a config file.

**Comment by zeucapua** [comment]
A few questions on how this should work: 
- Should this be a separate command eg `pizza generate config`?
- Should this automatically ran on `pizza generate codeowners` if not set already or instead stops it and give a log to the user to use `pizza generate config` first?
- Maybe an `--interactive` mode to add per email per user?

**Comment by jpmcb** [comment]
^ You're 100% on the right track @zeucapua.

> Should this be a separate command eg pizza generate config?

Yes, exactly, I'd imagine this would be a `pizza generate config` command.

> Maybe an --interactive mode to add per email per user?

I'd imagine this working with 2 modes: default mode and interactive mode.

The default mode would iterate git commits in the ref log, look at authors and their email mappings, and then generate the config as:

```yaml
attribution:
  John McBride:
    john@opensauced.pizza
  Brandon Roberts:
    brandon@opensauced.pizza
```

which is just a straight mapping of emails to names but is still a valid config (given someone may run this behind a firewall outside of the github ecosystem).

The other mode, interactive, would be abit more complex and build the keys of the mapping by interactively asking the user. It would look at emails for users and ask the user how to attribute the user to:

```
pizza generate config --interactive

Found email "john@opensauced.pizza" - how to attribute? > jpmcb
Attributing commits with author "john@opensauced.pizza" to "jpmcb"

Found email "brandon@opensauced.pizza" - how to attribute? > brandonroberts
Attributing commits with author "brandon@opensauced.pizza" to "brandonroberts"
```

And ultimately, this would create a config like:

```yaml
attribution:
  jpmcb:
    john@opensauced.pizza
  brandonroberts:
    brandon@opensauced.pizza
```

>  Should this automatically ran on pizza generate codeowners if not set already or instead stops it and give a log to the user to use pizza generate config first?

I think that could be a stretch goal. But if a config is not found, we could ask the user if they want to generate a config and then run the code within the `pizza generate config` command to quick go generate it.

---

You want to give this a stab @zeucapua ?

**Comment by zeucapua** [comment]
Yeah I can give this a shot!
